version: '3.1'

services:
  server:
    image: docker.minecolonies.com/chatchainserver:latest
    restart: always
    volumes:
      - chatchain-databases:/app/databases
    ports:
      - "8888:80"
    environment:
      - CLIENTS_AND_GROUPS_DATABASE=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@db:27017
      - ASPNETCORE_ENVIRONMENT=Development
      - IDENTITY_SERVER_URL=http://identity

  identity:
    image: docker.minecolonies.com/chatchainidentityserver:latest
    restart: always
    volumes:
      - chatchain-databases:/app/databases
    ports:
      - "8887:80"
    environment:
      - IDENTITY_SERVER_DATABASE=DataSource=databases/IS4.db
      - IDENTITY_SERVER_URL=http://identity

  webapp:
    image: docker.minecolonies.com/chatchainwebapp:latest
    restart: always
    volumes:
      - chatchain-databases:/app/databases
    ports:
    - "8886:80"
    environment:
      - IDENTITY_DATABASE=DataSource=databases/Identity.db
      - IDENTITY_SERVER_DATABASE=DataSource=databases/IS4.db

  db:
    image: mongo:3.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - chatchain-mongodb-databases:/data/db

volumes:
  chatchain-databases:
  chatchain-mongodb-databases:
  chatchain-ocelot-configuration:

networks:
  default: